import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
const root = fileURLToPath(new URL('.', import.meta.url));
const source = (await readFile(join(root, 'client-source.js'), 'utf8')).replace(/^export /gm, '');
const css = await readFile(join(root, 'client.css'), 'utf8');
// The only external is the host's own React. The browser does not load Node modules.
const bundle = `// Generated by node build-client.js; do not edit.\nwindow.__ModuleLoader__.load({\n  id: 'dsh-plugin-simple-pet',\n  factory(require) {\n    'use strict';\n${source}\n    const plugin = createSimplePetClient(require('react'));\n    const css = ${JSON.stringify(css)};\n    return { inject: plugin.inject, apply(ctx) {\n      ctx.effect(() => {\n        const tag = document.createElement('style');\n        tag.dataset.pluginCss = 'dsh-plugin-simple-pet/settings';\n        tag.textContent = css; document.head.appendChild(tag);\n        return () => tag.remove();\n      }, 'simple-pet: native settings style');\n      plugin.apply(ctx);\n    } };\n  }\n});\n`;
await mkdir(join(root, 'lib'), { recursive: true });
await writeFile(join(root, 'lib', 'client.js'), bundle, 'utf8');
console.log('Built lib/client.js: host-native settings section, shared React, owned CSS cleanup.');
